This is the translated version of the rm-controls.github.io
rm-controls/rm-controls.github.io pull request #10
Opened 2021-09-15 11:23 UTC by hw3579

The markdown has been translated to English version and it could work with two languages.

2021-09-15 15:31 UTC, qiayuanliao requested changes
code_sytle 是从英文翻译成中文的，你改的是原文... 不用改

2021-09-16 15:54 UTC, hw3579 commented
我把code_style 对照那个英文网站改了。。。

2021-09-16 15:55 UTC, hw3579 commented
不对不对
等等有点问题

2021-09-16 16:12 UTC, hw3579 commented
再看看？还有啥问题

2021-09-19 13:09 UTC, qiayuanliao commented
Commit 内容写清楚，分文件搞好，20个文件4个commit谁能Review？？？？

2021-09-19 14:41 UTC, closed without merging